keys:
  - &Liqyid-Medion age1ec3sk8vpus95h3gz8vz0nxn6l08zetyfqv5x6m536pmvv274fahs5emx45
  - &Liqyid-Loki age1qs3z8gd4xd2xx0zh940eylj6cxcrftc9xv6992mc0fka4ctdkvdq2deewp
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *Liqyid-Medion
      - *Liqyid-Loki
