return {
  -- { import = 'plugins.alpha' },
  { import = 'plugins.autopairs' },
  { import = 'plugins.autosession' },
  { import = 'plugins.colorizer' },
  { import = 'plugins.colorscheme' },
  { import = 'plugins.conform' },
  { import = 'plugins.debug' },
  { import = 'plugins.gitsigns' },
  { import = 'plugins.lint' },
  { import = 'plugins.lualine' },
  { import = 'plugins.mini' },
  { import = 'plugins.otter' },
  { import = 'plugins.rnvim' },
  { import = 'plugins.rustaceanvim' },
  { import = 'plugins.small_misc' },
  { import = 'plugins.snacks' },
  { import = 'plugins.treesitter' },
  { import = 'plugins.whichkey' },
}
